seleniumGrid = true
gridURL=http://192.168.0.100:4444


#Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Browser Configurations
browser = chrome

#Credentials
username = admin
password = admin123

#ImplicitWait
implicitWait = 10

#ExplicitWait
explicitWait = 30

